name: kap-helm
description: "This action creates a docker container with AWS CLI and Helm v3 installed for AWS EKS"
branding:
  icon: 'terminal'
  color: 'purple'
runs:
  using: 'docker'
  image: 'Dockerfile'
